class Menu:
    def press(self):
        print('              Presione la tecla de la opcion correspondiente           ')

    def principal(self):
        print('')
        print('')
        print('               APLICACION PARA EL ANALISIS DE METADATOS MD47           ')
        print('                                                                       ')
        print('                                                                       ')
        print('                   ____________________________________                ')
        print('                  |          MENU PRINCIPAL            |               ')
        print('                  |                                    |               ')
        print('                  |     1. ABRIR ARCHIVO               |               ')
        print('                  |                                    |               ')
        print('                  |     2. VER REGISTRO                |               ')
        print('                  |                                    |               ')
        print('                  |     3. MANTENIMIENTO DE LISTAS     |               ')
        print('                  |                                    |               ')
        print('                  |                                    |               ')
        print('                  |     X. SALIR                       |               ')
        print('                  |____________________________________|               ')
        print('                                                                       ')
        self.press()

    def file(self):
        print('')
        print('')
        print('               APLICACION PARA EL ANALISIS DE METADATOS MD47           ')
        print('                                                                       ')
        print('                                                                       ')
        print('                   ____________________________________                ')
        print('                  |         ANALISIS DE ARCHIVO        |               ')
        print('                  |                                    |               ')
        print('                  |     1. VER METADATOS               |               ')
        print('                  |                                    |               ')
        print('                  |     2. ANALIZAR                    |               ')
        print('                  |                                    |               ')
        print('                  |     3. LIMPIAR                     |               ')
        print('                  |                                    |               ')
        print('                  |                                    |               ')
        print('                  |     X. SALIR                       |               ')
        print('                  |____________________________________|               ')
        print('                                                                       ')
        self.press()

