# ------------------------- Definitions -----------------------
title = 'Limpiador de Metadatos MD47'
tIconBitMap = 'img/JTNEGRO.ico'
tWelcome = '\n\nMD47 Aplicación para Limpiar Metadatos \n\nTrabajo Fin de Máster\n\nJulio Gerardo Chinchilla Moya\n\nMáster Universitario en ' \
           'Ciberseguridad\n\nUniversidad de Alcalá de Henares, Madrid, España\n\n2019-2020\n\n\n\n*** SELECCIONE UN ARCHIVO PARA INICIAR ***'
tdSelectFile = 'Seleccione un Archivo para iniciar...'
tdPressAnalyze = '' #'\n*** Presione Analizar para continuar con el Análisis de Metadatos ***\n\n'
tdActionCleaning = 'Limpiando Archivo, por favor espere...'
tdActionCleaningOK = 'Se limpió correctamente...'
tdActionCleaningFailed = 'Ocurrió un error al limpiar, seleccione otro archivo.'

tFile = 'Archivo'
tMetadata = 'Metadatos'
tWordList = 'Lista de Palabras'
tAbout = 'Acerca de'
tSave = 'Guardar Resultado'
tClear = 'Limpiar Resultado'
tEdit = 'Modificar'
tUpdate = 'Actualizar'
tExit = 'Salir'
tSelect = 'Selecionar'
tAnalyze = 'Analizar'
tClean = 'Limpiar'

cPrimary = '#00838f'
cDark = '#005662'
cLight = '#4fb3bf'
tPrimary = '#ffffff'
tDark = '#ffffff'
tLight = '#000000'
cWhite = '#ffffff'
cBlack = '#000000'
cLightGray = '#e0e0e0'
cDarkGray = '#616161'