# ------------------------- Definitions -----------------------
title = 'Analizador de Metadatos MD47'
tIconBitMap = 'img/JTNEGRO.ico'
tdSelectFile = 'Seleccione un Archivo para iniciar...'
tdPressAnalyze = '\n*** Presione Analizar para continuar con el Análisis de Metadatos ***\n\n'

tFile = 'Archivo'
tMetadata = 'Metadatos'
tWordList = 'Lista de Palabras'
tAbout = 'Acerca de'
tSave = 'Guardar Resultado'
tClear = 'Limpiar Resultado'
tEdit = 'Modificar'
tUpdate = 'Actualizar'
tExit = 'Salir'
tSelect = 'Selecionar'
tAnalyze = 'Analizar'
tClean = 'Limpiar'

cPrimary = '#00838f'
cDark = '#005662'
cLight = '#4fb3bf'
tPrimary = '#ffffff'
tDark = '#ffffff'
tLight = '#000000'
cWhite = '#ffffff'
cBlack = '#000000'
cLightGray = '#e0e0e0'
cDarkGray = '#616161'